CLASS LHC_ZR_ZT_BATCH_CONFIG DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
        IMPORTING
           REQUEST requested_authorizations FOR ZR_ZT_BATCH_CONFIG
        RESULT result.
ENDCLASS.

CLASS LHC_ZR_ZT_BATCH_CONFIG IMPLEMENTATION.
  METHOD GET_GLOBAL_AUTHORIZATIONS.
  ENDMETHOD.
ENDCLASS.
